---
title: "Student opportunities"
description: |
  Last updated 2021-09-28.
output:
  distill::distill_article:
    toc: true
    toc_depth: 2    
---


**This is a *working* list of awards and competitions for (bio)statistics students and recent graduates.**


## Paper competitions

Many organizations and societies have annual paper competitions. Winners typically present the papers at the subsequent conferences. Awards often include travel cost.  

- [ASA Student Paper Competitions](https://www.amstat.org/ASA/Your-Career/Student-Paper-Competitions.aspx): Deadline is December 15. Submission details are specific for each section. 
- [ENAR Distinguished Student Paper Awards](https://www.enar.org/meetings/StudentPaperAwards/): Deadline is October 1. 


## Poster and presentation awards
- [SSC Student Research Presentation Award](https://ssc.ca/en/committees/student-research-presentation-award-committee)


## Travel awards

If you are short on funding for travel, consider applying for one of the travel awards listed below. To be eligible, you must be a member of the funding organization but student memberships are usually cheap. For example, IMS student membership is free and annual ASA student membership is USD 25.

- [IMS Hannan Graduate Student Travel Award](https://www.enar.org/meetings/StudentPaperAwards/): Deadline is February 1. Award amount is between USD 400 and USD 1000 per person. Open to Masters and PhD students. Travel to any IMS sponsored meetings, which include JSM and ENAR. 
- [ASA Student and Early Career Travel Fund](https://www.amstat.org/ASA/Your-Career/Awards/Student-and-Early-Career-Travel-Fund.aspx): Deadline is at least three months before the conference start date. Open to undergraduate and graduate students enrolled in a statistics or data science program. Travel to any ASA sponsored meetings.
- [CWS Travel Awards](https://cwstat.org/cws-travel-award/): Deadline varies. Open to early career professionals and PhD students in statistics or a related field. Travel to JSM.  
- [SPC Travel Scholarships](https://epiresearch.org/annual-meeting/awards/spc-travel-scholarships/): Deadline is September 30. Open to PhD students and postdocs. Travel to Society for Epidemiologic Research [Annual Meeting](https://epiresearch.org/annual-meeting/). 


## Scholarships

- [Gertrude M. Cox Scholarship](https://www.amstat.org/ASA/Your-Career/Awards/Gertrude-M-Cox-Scholarship.aspx): Deadline is February 23. Open to women PhD and Masters students who are citizens or permanent residents of US or Canada. Award amount is USD 1000.
